#!/usr/local/munkireport/munkireport-python3

import os
import subprocess
import sys
import re
import glob
import platform
import base64
from datetime import datetime, timedelta, tzinfo

sys.path.insert(0, '/usr/local/munki')
sys.path.insert(0, '/usr/local/munkireport')

from munkilib import FoundationPlist

def get_prefs():

    prefs = ""

    # Get all users' home folders
    cmd = ['/usr/bin/dscl', '.', '-readall', '/Users', 'NFSHomeDirectory']
    proc = subprocess.Popen(cmd, shell=False, bufsize=-1,
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    (output, unused_error) = proc.communicate()

    for user in output.decode().split('\n'):
        if 'NFSHomeDirectory' in user and '/var/empty' not in user:
            userpath = user.replace("NFSHomeDirectory: ", "")+'/Library/Preferences/MobileMeAccounts.plist'
            if os.path.isfile(userpath):
                prefs = prefs + userpath + "\n"

    return prefs[:-1]

def process_prefs(prefs):

    if prefs == "":
        return []

    out = []
    for pref in prefs.split('\n'):
        pl = FoundationPlist.readPlist(pref)
        for account in pl["Accounts"]:
            # Default logged_in to 1 (assume signed in if account exists)
            # Will be overridden by LoggedIn key if present
            preffile = {'account_id':'', 'logged_in': 1}
            for item in account:
                preffile['prefpath'] = pref.replace("/Library/Preferences/MobileMeAccounts.plist", "").replace("/Users/", "")
                if item == 'AccountAlternateDSID':
                    preffile['account_alternate_dsid'] = account[item]
                elif item == 'AccountDSID':
                    preffile['account_dsid'] = account[item]
                elif item == 'AccountDescription':
                    preffile['account_description'] = account[item]
                elif item == 'AccountID':
                    preffile['account_id'] = account[item]
                elif item == 'AccountUUID':
                    preffile['account_uuid'] = account[item]
                elif item == 'DisplayName':
                    preffile['display_name'] = account[item]
                elif item == 'LoggedIn':
                    # Use LoggedIn key if present (overrides default)
                    preffile['logged_in'] = to_bool(account[item])
                elif item == 'ShouldConfigure':
                    preffile['should_configure'] = to_bool(account[item])
                elif item == 'beta':
                    preffile['beta'] = to_bool(account[item])
#                elif item == 'firstName':
#                    preffile['first_name'] = account[item]
                elif item == 'isManagedAppleID':
                    preffile['is_managed_apple_id'] = to_bool(account[item])
#                elif item == 'lastName':
#                    preffile['last_name'] = account[item]
                elif item == 'primaryEmailVerified':
                    preffile['primary_email_verified'] = to_bool(account[item])
                elif item == 'Services':
                    for service in account[item]:
                        preffile[service['Name'].lower()+'_enabled'] = 0
                        # Show default of Siri enabled, if Darwin version is greater than 16 (Sierra)
                        # Because the Siri settings are stubborn
#                        if getOsVersion() > 16 and "SIRI" in service['Name']:
#                            preffile[service['Name'].lower()+'_enabled'] = 1
                        for serviceitem in service:
                            if "FAMILY" not in service['Name'] and "BACK_TO_MY_MAC" not in service['Name'] and serviceitem == 'Enabled' and to_bool(service[serviceitem]) == 1:
                                preffile[service['Name'].lower()+'_enabled'] = 1
                                preffile.update(get_extra_prefs(pref))
                            if "FAMILY" not in service['Name'] and "BACK_TO_MY_MAC" in service['Name'] and serviceitem == 'Enabled' and to_bool(service[serviceitem]) == 1:
                                preffile[service['Name'].lower()+'_enabled'] = 1  
                            elif serviceitem == 'status':
                                preffile[service['Name'].lower()+'_status'] = service[serviceitem]
                            elif serviceitem == 'showManageFamily':
                                preffile[service['Name'].lower()+'_show_manage_family'] = to_bool(service[serviceitem])
#                            elif serviceitem == 'apsEnv':
#                                preffile[service['Name'].lower()+'_aps_env'] = service[serviceitem]
#                            elif serviceitem == 'authMechanism':
#                                preffile[service['Name'].lower()+'_auth_mechanism'] = service[serviceitem]
#                            elif serviceitem == 'beta':
#                                preffile[service['Name'].lower()+'_beta'] = to_bool(service[serviceitem])
                            elif serviceitem == 'EmailAddress':
                                preffile[service['Name'].lower()+'_email_address'] = service[serviceitem]
                            elif serviceitem == 'FullUserName':
                                preffile[service['Name'].lower()+'_full_user_name'] = service[serviceitem]
                            elif serviceitem == 'Username':
                                preffile[service['Name'].lower()+'_username'] = service[serviceitem]
                            elif serviceitem == 'dotMacMailSupported':
                                preffile[service['Name'].lower()+'_dot_mac_mail_supported'] = to_bool(service[serviceitem])
#                            elif serviceitem == 'protocol':
#                                preffile[service['Name'].lower()+'_protocol'] = service[serviceitem]

            out.append(preffile)
    return out

def get_extra_prefs(pref):

    preffile = {}

    # Get iCloud Drive settings, if Darwin version is greater than 16 (Sierra)
    if getOsVersion() > 16:
        finderpath = pref.replace("MobileMeAccounts.plist", "com.apple.finder.plist")
        if os.path.isfile(finderpath):
            pl = FoundationPlist.readPlist(finderpath)
            preffile['clouddesktop_declined_upgrade'] = 0
            preffile['clouddesktop_desktop_enabled'] = 0
            preffile['clouddesktop_documents_enabled'] = 0
            preffile['clouddesktop_drive_enabled'] = 0
            preffile['clouddesktop_first_sync_down_complete'] = 0
            for item in pl:
                if item == 'FXICloudDriveDeclinedUpgrade':
                        preffile['clouddesktop_declined_upgrade'] = to_bool(pl[item])
                elif item == 'FXICloudDriveDesktop':
                        preffile['clouddesktop_desktop_enabled'] = to_bool(pl[item])
                elif item == 'FXICloudDriveDocuments':
                        preffile['clouddesktop_documents_enabled'] = to_bool(pl[item])
                elif item == 'FXICloudDriveEnabled':
                        preffile['clouddesktop_drive_enabled'] = to_bool(pl[item])
                elif item == 'FXICloudDriveFirstSyncDownComplete':
                        preffile['clouddesktop_first_sync_down_complete'] = to_bool(pl[item])

    # Try to get iCloud Photo Library settings
    try:
        photospath = pref.replace("Preferences/MobileMeAccounts.plist", "Containers/com.apple.CloudPhotosConfiguration/Data/Library/Preferences/com.apple.CloudPhotosConfiguration.plist")
        if os.path.isfile(photospath):
            pl = FoundationPlist.readPlist(photospath)
            preffile['cloud_photo_enabled'] = 0
            preffile['shared_streams_enabled'] = 0
            for item in pl:            
                if item == 'com.apple.photo.icloud.cloudphoto':
                        preffile['cloud_photo_enabled'] = to_bool(pl[item])
                elif item == 'com.apple.photo.icloud.sharedstreams':
                        preffile['shared_streams_enabled'] = to_bool(pl[item])
                elif item == 'service-preferences-com.apple.photo.icloud.cloudphoto':
                    for prefitem in pl[item]:
                        if prefitem == 'CPSPreferenceOnlyKeepThumbnailsKey':
                                preffile['cloud_photo_only_keep_thumbnail'] = to_bool(pl[item][prefitem])
    except:
        pass

    # Get iMessages in iCloud settings, if OS version is greater than 10.13.4 (Darwin 1750)
    if getOsVersionLonger() > 1750:
        madridpath = pref.replace("MobileMeAccounts.plist", "com.apple.madrid.plist")
        if os.path.isfile(madridpath):
            pl = FoundationPlist.readPlist(madridpath)
            preffile['imessage_syncing_enabled'] = 0
            preffile['imessage_currently_syncing'] = 0
            for item in pl:
                if item == 'CloudKitSyncingEnabled':
                    preffile['imessage_syncing_enabled'] = to_bool(pl[item])
                elif item == 'CloudKitIsSyncing':
                    preffile['imessage_currently_syncing'] = to_bool(pl[item])

    # Get Siri settings, if OS version is greater than 10.12 (Darwin 16)
    if getOsVersion() > 16:
        siripath = pref.replace("MobileMeAccounts.plist", "com.apple.assistant.backedup.plist")
        if os.path.isfile(siripath):
            pl = FoundationPlist.readPlist(siripath)
            preffile['siri_enabled'] = 0
            for item in pl:
                if item == 'Cloud Sync Enabled':
                    preffile['siri_enabled'] = to_bool(pl[item])

    return preffile

def to_bool(s):
    if s == True:
        return 1
    else:
        return 0

def getOsVersion():
    """Returns the Darwin version."""
    # Catalina -> 10.15.7 -> 19.6.0 -> 19
    # os_version_tuple = platform.mac_ver()[0].split('.')
    # return int(os_version_tuple[1])
    darwin_version_tuple = platform.release().split('.')
    return int(darwin_version_tuple[0])

def getOsVersionLonger():
    """Returns the full Darwin version."""
    # Catalina -> 10.15.7 -> 19.6.0 -> 1960
    # os_version_tuple = platform.mac_ver()[0].split('.')
    # return int(os_version_tuple[1])
    darwin_version_tuple = platform.release().replace(".","")
    return int(darwin_version_tuple)

def get_private_relay_status():
    """
    Get iCloud Private Relay status for the console user.
    Returns tuple (username, status) where status is 1 if enabled, 0 if disabled.
    Returns (None, None) if not available.
    Based on brunerd's iCloudPrivateRelayStatus.sh script.
    Only works on macOS 12 (Monterey) and later.
    """
    # Only for Monterey and up (macOS 12+, Darwin 21+)
    if getOsVersion() < 21:
        return (None, None)
    
    try:
        # Get the console user
        console_user_cmd = ['/usr/bin/stat', '-f', '%Su', '/dev/console']
        proc = subprocess.Popen(console_user_cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        console_user, _ = proc.communicate()
        console_user = console_user.decode().strip()
        
        if not console_user or console_user == 'root':
            return (None, None)
        
        # Get the console user's UID
        uid_cmd = ['/usr/bin/stat', '-f', '%u', '/dev/console']
        proc = subprocess.Popen(uid_cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        uid, _ = proc.communicate()
        uid = uid.decode().strip()
        
        # Export the preference domain data using launchctl asuser
        domain = 'com.apple.networkserviceproxy'
        export_cmd = ['/bin/launchctl', 'asuser', uid, 'sudo', '-u', console_user, 
                      '/usr/bin/defaults', 'export', domain, '-']
        proc = subprocess.Popen(export_cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        parent_data, _ = proc.communicate()
        
        if not parent_data:
            return (None, None)
        
        # Parse the parent plist
        parent_plist = FoundationPlist.readPlistFromString(parent_data)
        
        # Get the NSPServiceStatusManagerInfo key which contains embedded plist data
        if 'NSPServiceStatusManagerInfo' not in parent_plist:
            return (None, None)
        
        encoded_data = parent_plist['NSPServiceStatusManagerInfo']
        
        # Convert NSCFData to bytes
        decoded_data = bytes(encoded_data)
        
        # Parse the embedded plist
        embedded_plist = FoundationPlist.readPlistFromString(decoded_data)
        
        # Navigate to the PrivacyProxyServiceStatus
        # The structure is: $objects[1].PrivacyProxyServiceStatus
        if '$objects' in embedded_plist and len(embedded_plist['$objects']) > 1:
            obj = embedded_plist['$objects'][1]
            # Check if obj has keys (works for both dict and ObjC NSDictionary)
            if hasattr(obj, 'keys') and 'PrivacyProxyServiceStatus' in obj:
                status = obj['PrivacyProxyServiceStatus']
                return (console_user, 1 if status == 1 else 0)
        
        return (None, None)
        
    except Exception as e:
        # If anything fails, return None (unknown)
        return (None, None)

def main():
    """Main"""

    # Get information about iCloud accounts
    prefs = get_prefs()
    result = process_prefs(prefs)

    # Get Private Relay status for console user
    console_user, private_relay_status = get_private_relay_status()
    
    # Add Private Relay status only to the console user's account
    # prefpath contains the username (home folder name)
    if console_user is not None and private_relay_status is not None:
        for account in result:
            if 'prefpath' in account and account['prefpath'] == console_user:
                account['private_relay_enabled'] = private_relay_status

    # Write iCloud results to cache
    cachedir = '%s/cache' % os.path.dirname(os.path.realpath(__file__))
    output_plist = os.path.join(cachedir, 'icloud.plist')
    FoundationPlist.writePlist(result, output_plist)
    #print FoundationPlist.writePlistToString(result)

if __name__ == "__main__":
    main()
